//
//  TraceStroke.cpp -- A sequence of point samples from the curve generated by TraceKnotList
//  TodoSchool on Apr 22, 2016
//
//  Copyright (c) 2016 Enuma, Inc. All rights reserved.
//  See LICENSE.md for more details.
//

#include "TraceStroke.h"


BEGIN_NS_TRACEFIELD

void TraceStroke::appendPoint(const TracePoint& Point) {
    updateBoundingBox(Point.boundingBox(), SamplePoints.empty());
    SamplePoints.push_back(Point);
}

void TraceStroke::appendPoint(TracePoint&& Point) {
    updateBoundingBox(Point.boundingBox(), SamplePoints.empty());
    SamplePoints.push_back(std::move(Point));
}

const vector<TracePoint>& TraceStroke::samplePoints() const {
    return SamplePoints;
}

const Rect& TraceStroke::boundingBox() const {
    return BoundingBox;
}
    
void TraceStroke::updateBoundingBox(const Rect& BB, bool IsFirstInput) {
    BoundingBox = (IsFirstInput ? BB : BoundingBox.unionWithRect(BB));
}


}  // namespace tracefield
}  // namespace todoschool
