//
//  TraceStroke.h -- A sequence of point samples from the curve generated by TraceKnotList
//  TodoSchool on Apr 22, 2016
//
//  Copyright (c) 2016 Enuma, Inc. All rights reserved.
//  See LICENSE.md for more details.
//


#pragma once

#include "TracePoint.h"
#include "../Utils/MainNS.h"


BEGIN_NS_TRACEFIELD

class TraceStroke {
    vector<TracePoint> SamplePoints;
    Rect BoundingBox;

public:
    void appendPoint(const TracePoint& Point);
    void appendPoint(TracePoint&& Point);
    const vector<TracePoint>& samplePoints() const;

    const Rect& boundingBox() const;

private:
    void updateBoundingBox(const Rect& BB, bool IsFirstInput);
};

END_NS_TRACEFIELD
